### ISSUE TITLE
Add note, caption, subtitle options

### ISSUE THREAD

**Issue by santiago-afonso** [DiegoCiccia/StataPostProduce#1]
Great script! Here are some elements missing, hope that you can add them without too much trouble:

```
.note.text = {}
.note.text.Arrpush sample text
.caption.text = {}
.caption.text.Arrpush sample text
.subtitle.text = {}
.subtitle.text.Arrpush sample text
```
Thanks!

**Comment by DiegoCiccia** [comment]
Hey, thanks for the interest in the command and for providing grec syntax examples!
I have just added the options for note, caption and subtitle. You can just re-install the package using the same lines of code from the read me page.
Let me know if that works for you!
Diego
