### ISSUE TITLE
StataPostProduce is a most welcome project

### ISSUE THREAD

**Issue by ericmelse** [DiegoCiccia/StataPostProduce#2]
Dear Diego,

This `StataPostProduce` project is most welcome!
For me, it is very strange that Stata Corp. does not provide a proper documentation about `gr_edit` or `_gm_edit` (I have no idea where that is coming from either but it has its similar uses). I agree with what you wrote on your main StataPostProduce Github page. Using `gr_edit` is something of a 'last resort' when anything else fails. Typically, I use the graph editor to get some result that otherwise is not possible and basically solves some issue with a limitation of a user contributed package that does not offer an option to get what is required. The bonus of all the manual work that is involved, following this route, is that it is reproducible albeit with a whole stack of code. I suppose that is where your `StataPostProduce` could make our coding even more productive.
So, I am here to contribute and test as things proceed with StataPostProduce.

**Comment by DiegoCiccia** [comment]
Dear Eric,
Thanks a lot for your interest in StataPostProduce and commitment in helping the project!
Building on your proposal, the best thing you could do to contribute to StataPostProduce is to just use the recorder function in the graph editor and send me the resulting grec file. As I explained in the description, gr_postproduce is just a reverse engineering function from the gr_edit syntax, which can be explicitely retrieved when using the recorder option.
It would be for me extremely helpful if you could just take a Stata graph, open the recorder, change a lot of settings/add layers, close the recorder and send me the resulting grec file!
To do so, you should:
1. Load a graph in memory: e.g.
```stata
sysuse auto, clear
scatter price mpg
```
2. Click on "Start Graph Editor"
![fig1](https://github.com/DiegoCiccia/StataPostProduce/assets/71022390/c19f1d11-1e21-4ef0-8fe1-12bb7d595714)

3. Start recording
![fig2](https://github.com/DiegoCiccia/StataPostProduce/assets/71022390/1f4dddee-e051-411f-b500-447000803b07)

4. Make all the manual changes you want to see implemented in StataPostProduce through the graph editor (the more, the better!)
5. End the recording and save the file in whatever directory you want
![fig3](https://github.com/DiegoCiccia/StataPostProduce/assets/71022390/438b3e84-9ea2-4bd2-9f94-a207bf14e7b2)

7. Send the file to me via email (cicciadiego99@gmail.com).

Thanks in advance for you valuable collaboration!
I am planning on sending the package to SSC during the summer.
To this end, you interest and contribution are truly invaluable for reaching this objective.
Thanks again!
Best,
Diego
